import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Guru Portfolio | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hi, my name is Guru Balamurugan </h1>
        <h1 className={styles.title}>I am a Full Stack AI Developer</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
